### ISSUE TITLE
ES6 destructuring

### ISSUE THREAD

**Issue by krisimmig** [alvar0hurtad0/drupal-vuejs-todo#12]
https://github.com/alvar0hurtad0/drupal-vuejs-todo/blob/9e7855674dde0b391c6d3e71c6cb8d6271e61aa3/frontend/src/store/modules/todos/TodosMutations.js#L8

here you could use destructuring and object shorthand like so:

`
        [ADD_TODO](state, { id, body }) {
            state.todos.push({
                id,
                body,
                completed: false
            })
        },
`

**Comment by alvar0hurtad0** [comment]
Thanks a lot for your review @krisimmig
