### ISSUE TITLE
Duplicating the find method here

### ISSUE THREAD

**Issue by krisimmig** [alvar0hurtad0/drupal-vuejs-todo#13]
https://github.com/alvar0hurtad0/drupal-vuejs-todo/blob/9e7855674dde0b391c6d3e71c6cb8d6271e61aa3/frontend/src/store/modules/todos/TodosMutations.js#L29

Probably better to just do the .find once, save it and than do the mutation.
`
 let t = state.todos.find(todo => todo.id === payload)

 t.completed = !t.completed; 
`

**Comment by alvar0hurtad0** [comment]
Thanks a lot for your review @krisimmig
